# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_code', models.CharField(max_length=100)),
                ('faculty_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_surname', models.CharField(max_length=100)),
                ('graduate_name', models.CharField(max_length=100)),
                ('graduate_patronymic', models.CharField(blank=True, max_length=100)),
                ('graduate_birthdate', models.DateField()),
                ('graduate_photo', models.ImageField(blank=True, upload_to='')),
                ('graduate_address', models.TextField(default='')),
                ('graduate_workplace', models.CharField(max_length=100)),
                ('graduate_science_work', models.TextField()),
                ('graduate_diploma_theme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GradYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradyear_year', models.CharField(max_length=4)),
                ('gradyear_degree', models.CharField(choices=[('B', 'Бакалавр'), ('S', 'Специалист')], default='B', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaf_name', models.CharField(max_length=100)),
                ('kaf_code', models.CharField(max_length=100)),
                ('kaf_description', models.TextField()),
                ('kaf_site', models.CharField(max_length=100)),
                ('kaf_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=250)),
                ('speciality_code', models.CharField(max_length=30)),
                ('speciality_description', models.TextField()),
                ('speciality_kaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Kaf')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.AddField(
            model_name='gradyear',
            name='gradyear_speciality',
            field=models.ManyToManyField(to='graduates.Speciality'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='graduate_speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Speciality'),
        ),
    ]
