# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_code', models.CharField(max_length=100)),
                ('faculty_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Факультеты',
                'verbose_name': 'Факультет',
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_surname', models.CharField(max_length=100)),
                ('graduate_name', models.CharField(max_length=100)),
                ('graduate_patronymic', models.CharField(blank=True, max_length=100)),
                ('graduate_birthdate', models.DateField()),
                ('graduate_address', models.TextField(default='')),
                ('graduate_workplace', models.CharField(max_length=100)),
                ('graduate_science_work', models.TextField()),
                ('graduate_diploma_theme', models.CharField(max_length=100)),
                ('graduate_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Faculty')),
            ],
            options={
                'verbose_name_plural': 'Выпускники',
                'ordering': ['graduate_surname'],
                'verbose_name': 'Выпускник',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=10)),
                ('group_end_year', models.CharField(default='2010', max_length=4)),
                ('group_degree', models.CharField(choices=[('Бакалавр', 'Бакалавр'), ('Специалист', 'Специалист')], default='Бакалавр', max_length=20)),
                ('group_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Faculty')),
            ],
            options={
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['group_number'],
                'verbose_name': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Kaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaf_name', models.CharField(max_length=100)),
                ('kaf_code', models.CharField(max_length=100)),
                ('kaf_description', models.TextField()),
                ('kaf_site', models.CharField(blank=True, max_length=100)),
                ('kaf_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Faculty')),
            ],
            options={
                'verbose_name_plural': 'Кафедры',
                'verbose_name': 'Кафедра',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=250)),
                ('speciality_code', models.CharField(max_length=30)),
                ('speciality_description', models.TextField()),
                ('speciality_kaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Kaf')),
            ],
            options={
                'verbose_name_plural': 'Специальности',
                'verbose_name': 'Специальность',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_kaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Kaf'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_speciality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='graduates.Speciality'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='graduate_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Group'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='graduate_kaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Kaf'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='graduate_speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.Speciality'),
        ),
    ]
