# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradyear',
            name='gradyear_speciality',
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_gradyear',
            field=models.ManyToManyField(to='graduates.GradYear'),
        ),
    ]
