# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_auto_20160420_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='speciality_gradyear',
        ),
        migrations.AddField(
            model_name='graduate',
            name='graduate_degree',
            field=models.CharField(choices=[('B', 'Бакалавр'), ('S', 'Специалист')], default='B', max_length=20),
        ),
        migrations.AddField(
            model_name='graduate',
            name='graduate_gradyear',
            field=models.CharField(default=datetime.datetime(2016, 4, 21, 19, 2, 20, 351044, tzinfo=utc), max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kaf',
            name='kaf_site',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='GradYear',
        ),
    ]
