# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0003_auto_20160421_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='graduate_degree',
            field=models.CharField(choices=[('Бакалавр', 'Бакалавр'), ('Специалист', 'Специалист')], default='B', max_length=20),
        ),
    ]
